### ISSUE TITLE
[TODO] 能否把搁置和抛弃的番剧过滤掉？

### ISSUE THREAD

**Issue by mrzhu666** [DrRyanHuang/bangumi-anime#2]
过滤掉搁置和抛弃的番剧。最好有个参数，可以选择是否过滤掉想看和再看的番剧吧

**Comment by DrRyanHuang** [comment]
已在该commit更新完毕：https://github.com/DrRyanHuang/bangumi-anime/commit/af71b4c6d9c16b9c5ca0542205f1661c2fc3b301


可以修改这一行来配置，目前已更新为只保留想看、看过和在看

https://github.com/DrRyanHuang/bangumi-anime/blob/38e11d825602f2338608fc27e22b28e64b231ccf/config.py#L32

anime_type 可选参数：
```
anime_type =>
1 => 想看
2 => 看过
3 => 在看
4 => 搁置
5 => 抛弃
```
